language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

script:
    - phpunit --configuration tests/phpunit.xml
    - ./vendor/bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

before_script: composer install
