language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0

script:
    - phpunit --configuration tests/phpunit.xml
    - ./vendor/bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

before_script: composer install
